name = "qingstor"

[namespace.service.new]
required = ["credential"]
optional = ["endpoint", "http_client_options", "pair_policy", "default_service_pair"]

[namespace.service.op.create]
required = ["location"]

[namespace.service.op.delete]
optional = ["location"]

[namespace.service.op.get]
optional = ["location"]

[namespace.service.op.list]
optional = ["location"]

[namespace.storage]
implement = ["copier", "fetcher", "mover", "multiparter", "reacher"]

[namespace.storage.new]
required = ["name"]
optional = ["disable_uri_cleaning", "http_client_options", "location", "pair_policy", "work_dir", "default_storage_pair"]

[namespace.storage.op.delete]
optional = ["multipart_id"]

[namespace.storage.op.list]
optional = ["list_mode"]

[namespace.storage.op.reach]
required = ["expire"]

[namespace.storage.op.read]
optional = ["offset", "io_callback", "size"]

[namespace.storage.op.write]
optional = ["content_md5", "content_type", "io_callback", "storage_class"]

[pairs.disable_uri_cleaning]
type = "bool"

[pairs.storage_class]
type = "string"

[pairs.default_service_pair]
type = "DefaultServicePairs"
description = "set default pairs for service actions"

[pairs.default_storage_pair]
type = "DefaultStoragePairs"
description = "set default pairs for storager actions"

[infos.object.meta.storage-class]
type = "string"